from core.views import event_output

# This code automatically generated by ezo.  Only modify where suggested.
#
# data is an instance of ContractEvent
# contract is the calling instance of Contract - it is used to send a response



def handler(data, contract):

    event_name = '{event_name}'

    ### put your code here

    event_output(contract, event_name, data)

    ### uncomment the code below to build a response object
    # response = dict()
    # response["address"] = data.address  # <<< the contract's address from the data
    # response["function"] = None         # <<< replace None with the Contract function that will be called
    # response["params"] = None           # <<< replace None with a list of your function's data parameters
    # response["target"] = data.target    # <<< the target network for the response

    ### uncomment the code below to send a response to the contract function
    # _, err = contract.response(response)
    # if err:
    #     return None, err

    return None, None